version: 0.2

phases:
  install:
    commands:
      - echo Installing yarn
      - npm install -g yarn
      - echo Installing packages via npm...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.js
    - views/**/*
    - routes/**/*
    - public/**/*
    - node_modules/**/*
    - bin/**/*
